from __future__ import annotations

import asyncio
from pathlib import Path
from types import SimpleNamespace

import pytest
from fastapi.testclient import TestClient

from agentchatroom import mcp_server
from agentchatroom.api import create_app
from agentchatroom.config import Settings, load_settings
from agentchatroom.contracts import MCP_CONTEXT_EVENT_TYPES
from agentchatroom.errors import DomainError
from agentchatroom.project_registration import register_checkout_project
from agentchatroom.services import AgentChatRoomService, normalize_project_settings
from tests.conftest import join_room_with_workspace


def _call_tool(name: str, arguments: dict | None = None, context=None):
    return asyncio.run(
        mcp_server.mcp._tool_manager.call_tool(
            name,
            arguments or {},
            context=context,
        )
    )


def test_normalize_project_settings_mcp_message_limit():
    # Valid boundaries
    norm1 = normalize_project_settings({"mcp_message_limit": 1})
    assert norm1["mcp_message_limit"] == 1
    assert norm1["mcp_message_context_limit"] == 1

    norm10 = normalize_project_settings({"mcp_message_limit": 10})
    assert norm10["mcp_message_limit"] == 10
    assert norm10["mcp_message_context_limit"] == 10

    # Default value
    norm_default = normalize_project_settings({})
    assert norm_default["mcp_message_limit"] == 5
    assert norm_default["mcp_message_context_limit"] == 5

    # Dual-naming compatibility
    norm_alias = normalize_project_settings({"mcp_message_context_limit": 7})
    assert norm_alias["mcp_message_limit"] == 7
    assert norm_alias["mcp_message_context_limit"] == 7

    # Invalid values: out of range, wrong types
    for invalid in (0, -1, 11, 100, "5", True, False, 3.5, None):
        with pytest.raises(DomainError) as exc_info:
            normalize_project_settings({"mcp_message_limit": invalid})
        assert exc_info.value.code == "invalid_project_settings"


def test_config_load_settings_mcp_message_limit(monkeypatch, tmp_path):
    monkeypatch.setenv("AGENTCHATROOM_DATA_DIR", str(tmp_path / "data"))

    # Default
    settings = load_settings()
    assert settings.mcp_message_limit == 5

    # Environment variable override
    monkeypatch.setenv("AGENTCHATROOM_MCP_MESSAGE_LIMIT", "8")
    settings = load_settings()
    assert settings.mcp_message_limit == 8

    # Invalid env var raises ValueError
    monkeypatch.setenv("AGENTCHATROOM_MCP_MESSAGE_LIMIT", "99")
    with pytest.raises(ValueError, match="mcp_message_limit"):
        load_settings()

    monkeypatch.setenv("AGENTCHATROOM_MCP_MESSAGE_LIMIT", "not-a-number")
    with pytest.raises(ValueError):
        load_settings()


def test_mcp_context_filtering_and_boundaries(service, project, joined_agents):
    executor, reviewer = joined_agents

    # Generate various events:
    # 1. Joins are already generated by joined_agents fixture.
    # 2. Add task creation, claim, and update (system/task events)
    task = service.create_task(
        project["id"],
        title="Test Task",
        acceptance_criteria=["Criteria 1"],
    )["task"]
    service.claim_task(
        project["id"],
        task["id"],
        executor["agent"]["id"],
        executor["token"],
    )

    # 3. Add file lease acquire and release
    lease = service.acquire_lease(
        project["id"],
        session_id=executor["agent"]["id"],
        token=executor["token"],
        path_pattern="src/test.py",
        mode="exclusive",
    )["lease"]
    service.release_lease(
        project["id"],
        lease["id"],
        session_id=executor["agent"]["id"],
        token=executor["token"],
    )

    # 4. Add system message
    service.post_message(
        project["id"],
        body="System broadcast",
        kind="system",
        session_id=executor["agent"]["id"],
        token=executor["token"],
        model_display_name="system",
    )

    # 5. Add 12 valid agent messages of mixed types
    message_event_ids = []
    for i in range(12):
        if i % 3 == 0:
            mkind = "message"
        elif i % 3 == 1:
            mkind = "decision"
        else:
            mkind = "blocker"
        msg = service.post_message(
            project["id"],
            body=f"Valid message #{i + 1}",
            kind=mkind,
            session_id=executor["agent"]["id"],
            token=executor["token"],
            model_display_name="test-model",
        )
        message_event_ids.append(msg["event_id"])

    # Test default limit (5) in mcp_context
    result = service.room_sync(
        project["id"],
        session_id=reviewer["agent"]["id"],
        token=reviewer["token"],
        mcp_context=True,
        initial_inject=True,
    )
    events = result["events"]
    assert len(events) == 5

    # All events must strictly belong to MCP_CONTEXT_EVENT_TYPES
    for ev in events:
        assert ev["event_type"] in MCP_CONTEXT_EVENT_TYPES

    # Must be the last 5 messages in chronological ascending order
    expected_ids = message_event_ids[-5:]
    assert [ev["id"] for ev in events] == expected_ids
    assert events[0]["id"] < events[-1]["id"]

    # Test custom limit = 1
    service.update_project(project["id"], settings={"mcp_message_limit": 1})
    result_1 = service.room_sync(
        project["id"],
        session_id=reviewer["agent"]["id"],
        token=reviewer["token"],
        mcp_context=True,
        initial_inject=True,
    )
    assert len(result_1["events"]) == 1
    assert result_1["events"][0]["id"] == message_event_ids[-1]

    # Test custom limit = 10
    service.update_project(project["id"], settings={"mcp_message_limit": 10})
    result_10 = service.room_sync(
        project["id"],
        session_id=reviewer["agent"]["id"],
        token=reviewer["token"],
        mcp_context=True,
        initial_inject=True,
    )
    assert len(result_10["events"]) == 10
    assert [ev["id"] for ev in result_10["events"]] == message_event_ids[-10:]


def test_mcp_cursor_and_repeated_sync(service, project, joined_agents):
    executor, reviewer = joined_agents

    for i in range(8):
        service.post_message(
            project["id"],
            body=f"Message {i}",
            kind="message",
            session_id=executor["agent"]["id"],
            token=executor["token"],
            model_display_name="test-model",
        )

    # First sync with initial_inject=True (like room_bootstrap)
    first_sync = service.room_sync(
        project["id"],
        session_id=reviewer["agent"]["id"],
        token=reviewer["token"],
        mcp_context=True,
        initial_inject=True,
    )
    assert len(first_sync["events"]) == 5
    last_cursor = first_sync["cursor"]

    # Immediate second sync without 'after' should NOT re-return full history or dump 200 events
    second_sync = service.room_sync(
        project["id"],
        session_id=reviewer["agent"]["id"],
        token=reviewer["token"],
        mcp_context=True,
    )
    assert len(second_sync["events"]) == 0
    assert second_sync["cursor"] == last_cursor

    # Post 2 new messages
    new_msg1 = service.post_message(
        project["id"],
        body="New message 1",
        kind="decision",
        session_id=executor["agent"]["id"],
        token=executor["token"],
        model_display_name="test-model",
    )
    new_msg2 = service.post_message(
        project["id"],
        body="New message 2",
        kind="blocker",
        session_id=executor["agent"]["id"],
        token=executor["token"],
        model_display_name="test-model",
    )

    # Next sync should only return the 2 new messages
    third_sync = service.room_sync(
        project["id"],
        session_id=reviewer["agent"]["id"],
        token=reviewer["token"],
        mcp_context=True,
    )
    assert len(third_sync["events"]) == 2
    assert [ev["id"] for ev in third_sync["events"]] == [new_msg1["event_id"], new_msg2["event_id"]]


def test_configuration_precedence(monkeypatch, tmp_path, service, project, joined_agents):
    executor, reviewer = joined_agents

    for i in range(10):
        service.post_message(
            project["id"],
            body=f"Precedence msg {i}",
            kind="message",
            session_id=executor["agent"]["id"],
            token=executor["token"],
            model_display_name="test-model",
        )

    # 1. Project settings has highest precedence (set to 3)
    service.update_project(project["id"], settings={"mcp_message_limit": 3})
    monkeypatch.setenv("AGENTCHATROOM_MCP_MESSAGE_LIMIT", "7")
    res = service.room_sync(
        project["id"],
        session_id=reviewer["agent"]["id"],
        token=reviewer["token"],
        mcp_context=True,
        initial_inject=True,
    )
    assert len(res["events"]) == 3

    # 2. When project settings has no explicit limit (e.g. legacy), env var takes precedence
    with service.database.connect(write=True) as conn:
        conn.execute("UPDATE projects SET settings_json = '{}' WHERE id = ?", (project["id"],))
    import dataclasses
    custom_settings = dataclasses.replace(service.settings, mcp_message_limit=4)
    monkeypatch.setattr(service, "settings", custom_settings)
    monkeypatch.setenv("AGENTCHATROOM_MCP_MESSAGE_LIMIT", "7")
    assert service.get_project_mcp_message_limit(project["id"]) == 7

    # 3. If env var is removed, should resolve to service.settings (4)
    monkeypatch.delenv("AGENTCHATROOM_MCP_MESSAGE_LIMIT", raising=False)
    assert service.get_project_mcp_message_limit(project["id"]) == 4


def test_api_project_settings_persistence(service, project):
    app = create_app(service.settings)
    client = TestClient(app)

    # Get current settings via snapshot
    resp = client.get(f"/api/v1/projects/{project['id']}/snapshot")
    assert resp.status_code == 200
    assert resp.json()["project"]["settings"]["mcp_message_limit"] == 5

    # PATCH with valid limit 8
    patch_resp = client.patch(
        f"/api/v1/projects/{project['id']}",
        json={"settings": {"mcp_message_limit": 8}},
    )
    assert patch_resp.status_code == 200
    assert patch_resp.json()["project"]["settings"]["mcp_message_limit"] == 8

    # Verify persistence via snapshot
    get_resp = client.get(f"/api/v1/projects/{project['id']}/snapshot")
    assert get_resp.status_code == 200
    assert get_resp.json()["project"]["settings"]["mcp_message_limit"] == 8

    # PATCH with invalid values should fail with 400
    for invalid in (0, 11, -1, "8"):
        bad_resp = client.patch(
            f"/api/v1/projects/{project['id']}",
            json={"settings": {"mcp_message_limit": invalid}},
        )
        assert bad_resp.status_code == 400
        assert bad_resp.json()["error"]["code"] == "invalid_project_settings"


def test_audit_integrity_and_task_history_remain_untrimmed(service, project, joined_agents):
    executor, reviewer = joined_agents

    # Create task, lease, system message, agent messages
    task = service.create_task(
        project["id"],
        title="Audit Task",
        acceptance_criteria=["Criterion"],
    )["task"]
    service.claim_task(
        project["id"],
        task["id"],
        executor["agent"]["id"],
        executor["token"],
    )

    lease = service.acquire_lease(
        project["id"],
        session_id=executor["agent"]["id"],
        token=executor["token"],
        path_pattern="README.md",
        mode="exclusive",
    )["lease"]
    service.release_lease(
        project["id"],
        lease["id"],
        session_id=executor["agent"]["id"],
        token=executor["token"],
    )

    for i in range(15):
        service.post_message(
            project["id"],
            body=f"Audit message {i}",
            kind="message",
            session_id=executor["agent"]["id"],
            token=executor["token"],
            model_display_name="test-model",
        )

    # 1. MCP sync has limit 5
    mcp_result = service.room_sync(
        project["id"],
        session_id=reviewer["agent"]["id"],
        token=reviewer["token"],
        mcp_context=True,
        initial_inject=True,
    )
    assert len(mcp_result["events"]) == 5

    # 2. Non-MCP sync (regular room_sync without mcp_context) returns all events from after
    full_sync = service.room_sync(project["id"], after=0)
    assert len(full_sync["events"]) > 15

    # 3. Audit query returns ALL events (joins, task events, lease events, messages)
    audit = service.query_audit(project["id"], limit=1000)
    event_types = {e["event_type"] for e in audit["events"]}
    assert "agent.joined" in event_types
    assert "task.created" in event_types
    assert "task.claimed" in event_types
    assert "lease.acquired" in event_types
    assert "lease.released" in event_types
    assert "message.message" in event_types

    # 4. Task history returns task events untrimmed
    task_hist = service.list_task_history(project["id"], task["id"])
    task_types = {e["event_type"] for e in task_hist["items"]}
    assert "task.created" in task_types
    assert "task.claimed" in task_types


def test_room_bootstrap_message_projection(monkeypatch, service, project_dir):
    monkeypatch.setenv(mcp_server.SOFTWARE_KEY_ENV, "boot-agent")
    monkeypatch.setenv(mcp_server.SOFTWARE_NAME_ENV, "Boot Agent")
    monkeypatch.setenv(mcp_server.SOFTWARE_CLIENT_ENV, "codex")
    monkeypatch.setattr(mcp_server, "service", service)

    project = service.create_project(root_path=str(project_dir), name="Bootstrap Room")
    register_checkout_project(project_dir, project)
    service.update_project(project["id"], settings={"mcp_message_limit": 4})

    # Join an agent to post messages
    joined = join_room_with_workspace(
        service,
        project,
        agent_key="other-agent",
        name="Other",
        client="codex",
        model="test-model",
    )

    # Post system message and 8 agent messages
    service.post_message(
        project["id"],
        body="System warning",
        kind="system",
        session_id=joined["agent"]["id"],
        token=joined["token"],
        model_display_name="system",
    )
    for i in range(8):
        service.post_message(
            project["id"],
            body=f"Bootstrap msg {i}",
            kind="message",
            session_id=joined["agent"]["id"],
            token=joined["token"],
            model_display_name="test-model",
        )

    class FakeContext:
        def __init__(self, uri: str) -> None:
            async def list_roots():
                return SimpleNamespace(roots=[SimpleNamespace(uri=uri)])

            self.request_context = SimpleNamespace(
                session=SimpleNamespace(list_roots=list_roots, session_id="boot-sess-1")
            )

    monkeypatch.chdir(project_dir)
    res = _call_tool(
        "room_bootstrap",
        {},
        context=FakeContext(project_dir.resolve().as_uri()),
    )
    assert res["ok"] is True
    # Injected messages must be exactly 4 (configured limit)
    messages = res["result"]["messages"]
    assert len(messages) == 4
    for msg in messages:
        assert msg["event_type"] == "message.message"
    assert [m["payload"]["body"] for m in messages] == [
        "Bootstrap msg 4",
        "Bootstrap msg 5",
        "Bootstrap msg 6",
        "Bootstrap msg 7",
    ]